/**
 * This file was auto-generated by a tool. It provides types for the backend.
 * Do not modify this file manually.
 */
export type Conversation = {
  /**
   * Unique identifier for the Conversation entity.
   */
  id: string;
  /**
   * Timestamp indicating when the conversation was initiated.
   */
  createdAt: string;
  /**
   * Timestamp indicating the last time the conversation was updated.
   */
  updatedAt: string;
};
export type Message = {
  /**
   * Unique identifier for the Message entity.
   */
  id: string;
  /**
   * Reference to Conversation. (Relationship: Conversation 1:N Message)
   */
  conversationId: string;
  /**
   * Indicates who sent the message (e.g., 'user', 'ai').
   */
  sender: string;
  /**
   * The text content of the message.
   */
  content: string;
  /**
   * Timestamp indicating when the message was sent.
   */
  timestamp: string;
};
export type UserProfileSummary = {
  /**
   * Unique identifier for the UserProfileSummary entity.
   */
  id: string;
  /**
   * Reference to Conversation. (Relationship: Conversation 1:1 UserProfileSummary)
   */
  conversationId: string;
  /**
   * A brief, AI-generated textual summary of the user's inferred interests and skills.
   */
  summaryText: string;
  /**
   * An array of keywords or phrases representing the specific interests and skills inferred by the AI.
   */
  inferredInterests: string[];
  /**
   * An array of user preferences like 'creative' or 'logical'.
   */
  preferences?: string[];
  /**
   * An array of user goals like 'learn a new language'.
   */
  goals?: string[];
  /**
   * Timestamp indicating when the summary was last updated.
   */
  updatedAt: string;
};
export type ProjectRecommendation = {
  /**
   * Unique identifier for the ProjectRecommendation entity.
   */
  id: string;
  /**
   * Reference to Conversation. (Relationship: Conversation 1:N ProjectRecommendation)
   */
  conversationId: string;
  /**
   * The title of the recommended project.
   */
  title: string;
  /**
   * A detailed description of the project idea, including its goals and potential technologies.
   */
  description: string;
  /**
   * The sequential order of this recommendation within a set of projects (e.g., 1, 2, or 3).
   */
  order: number;
  /**
   * A personalized explanation of why the project fits the user.
   */
  whyItMatchesUser: string;
  /**
   * A comma-separated list of recommended technologies.
   */
  techStack: string;
  /**
   * The project's difficulty level (e.g., Easy, Medium, Hard).
   */
  difficulty: string;
  /**
   * A summary of why the project is valuable for a resume.
   */
  resumeValue: string;
  /**
   * A step-by-step project roadmap.
   */
  roadmap: {
    learn: string;
    buildFirst: string;
    advanced: string;
  };
  /**
   * Indicates if the project is bookmarked by the user.
   */
  isBookmarked?: boolean;
};

export type BenchmarkProject = {
  /**
   * Unique identifier for the BenchmarkProject entity.
   */
  id: string;
  /**
   * The title of the problem statement.
   */
  title: string;
  /**
   * A detailed description of the problem statement.
   */
  description: string;
  /**
   * The category of the problem statement (e.g., 'Web Dev', 'AI').
   */
  category: string;
  /**
   * The difficulty level (e.g., 'Beginner', 'Intermediate', 'Advanced').
   */
  difficulty: string;
  /**
   * Number of upvotes from the community.
   */
  upvotes: number;
  /**
   * The UID of the user who seeded this project (if any).
   */
  seededByUserId?: string;
  /**
   * Whether the seeding user is currently building this project.
   */
  isBuildingThis?: boolean;
  /**
   * Whether the seeding user has completed this project.
   */
  isCompleted?: boolean;
  /**
   * Whether the seeding user would recommend this project to others.
   */
  wouldRecommend?: boolean;
  /**
   * The tech stack of the project, carried from the recommendation.
   */
  techStack?: string;
};